stock/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    # /stock/
    url(r'^$', views.first, name='home'),


    # /stock/<pk>/
    url(r'^(?P<pid>[0-9]+)/$', views.detailview, name='detail'),

    # /stock/<pk>/addtolist
    url(r'^(?P<pid>[0-9]+)/addtolist/$', views.addtolist, name='addtolist'),

    # /stock/<pk>/remove
    url(r'^(?P<pid>[0-9]+)/remove/$', views.remove, name='remove'),

    # /stock/about/
    url(r'^about/$', views.about, name='about'),

    # /stock/services/
    url(r'^services/$', views.services, name='services'),

    # /stock/contact/
    url(r'^contact/$', views.contact, name='contact'),


    # /stock/dashboard/
    url(r'^dashboard/$', views.dashboard, name='dashboard'),

    # /stock/search/
    url(r'^search/$', views.search, name='search'),

    # /stock/noti/
    url(r'^noti/$', views.noti, name='noti'),

    # /stock/profile/
    url(r'^profile/$', views.paaa, name='profile'),

    # /stock/profile/edit/
    url(r'^profile/edit/$', views.edit, name='edit'),

    # /stock/register/
    url(r'^register/$', views.profileregister, name='register'),

    # /stock/logout/
    url(r'^logout/$', views.logout_view, name='logout'),

    # /stock/register/bakwas/
    url(r'^register/bakwas/$', views.gita, name=''),





    # /stock/all/
    url(r'^all/$', views.listview, name='all'),


    # /stock/feed/
    #url(r'^feed/$', views.git, name='33rwdfwefefewefwefwf'),

    # /stock/all/(0,1,2)/<page no>/
    url(r'^all/(?P<fby>[0-5]{1})/(?P<page>[0-9]+)/$', views.pagi, name='k'),

]

stockjuaari/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from stock import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^stock/', include('stock.urls')),
    url(r'^$', views.login_view , name='login'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

stock/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class singlestock(models.Model):
    name = models.CharField(max_length=20)
    sector = models.CharField(max_length=20)
    cap = models.CharField(max_length=20)
    last_trade_price = models.FloatField()
    high = models.FloatField()
    low = models.FloatField()
    yearly = models.FloatField()
    q1 = models.FloatField()
    q2 = models.FloatField()
    q3 = models.FloatField()
    hold = models.BooleanField(default=False)

    def __str__(self):
        return self.name +" - " +self.sector

class profile(models.Model):
    name = models.CharField(max_length=100)
    photo = models.FileField()
    user_ref = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.IntegerField(default=0)
    company = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    stocks = models.ManyToManyField(singlestock)

    def __str__(self):
        return self.name + " " +self.company + " "+ str(self.age)

class feedback(models.Model):
    name = models.CharField(max_length=50)
    content = models.CharField(max_length=1000)


    def __str__(self):
        return self.name

stock/forms.py
from django import forms
from .models import profile
from django.forms import ModelForm

'''
class NameForm(forms.ModelForm):
    class Meta:
        model = testmodel
        fields = ('name','age','date_of_birth')
'''

class ProfileForm(forms.Form):
    name= forms.CharField(max_length=50)
    email_ID= forms.CharField(max_length=50)
    password= forms.CharField(min_length=8, widget=forms.PasswordInput)
    confirm_password= forms.CharField(min_length=8, widget=forms.PasswordInput)
    company = forms.CharField(max_length=80)

class LoginForm(forms.Form):
    email_id= forms.CharField(max_length=50)
    password= forms.CharField(min_length=8, widget=forms.PasswordInput)

class FeedbackForm(forms.Form):
    name= forms.CharField(max_length=50)
    content= forms.CharField(max_length=1000)


class poForm(forms.Form):
    age= forms.IntegerField()
    company= forms.CharField(max_length=50)

class upform(ModelForm):
    class Meta:
        model = profile
        fields = ['name', 'photo', 'age', 'company', 'email', 'stocks']

stock/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from .models import singlestock, profile, feedback
from .forms import ProfileForm, LoginForm, FeedbackForm, upform, poForm
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from random import randint
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .dbfeeder import ourdata


import feedparser
feeds = feedparser.parse('http://feeds.marketwatch.com/marketwatch/realtimeheadlines/')
# Create your views here.

def gita(request):

    return render(request, 'stock/bakwas.html', {})


def git(request):

#9148464923
    data = ourdata()
    data['Yearly'] = data['Yearly'].astype(float)
    data['Q1'] = data['Q1'].astype(float)
    data['Q2'] = data['Q2'].astype(float)
    data['Q3'] = data['Q3'].astype(float)
    data['Share'] = data['Share'].astype(str)
    data['Sector'] = data['Sector'].astype(str)
    data['Cap Category'] = data['Cap Category'].astype(str)
    data['Category'] = data['Category'].astype(str)
    print(data.dtypes)
    for d in [data]:
        d['Category'] = d['Category'].map({'YES': 'True', 'NO': 'False'})
    data['Category'] = data['Category'].astype(bool)
    print(data.dtypes)
    for i in range(len(data)):
        singlestock.objects.create(name=data['Share'][i], sector=data['Sector'][i], cap=data['Cap Category'][i],
                                   last_trade_price=data['Last Traded Price'][i], high=data['High Price'][i], low=data['Low Price'][i],
                                   yearly=data['Yearly'][i], q1=data['Q1'][i], q2=data['Q2'][i], q3=data['Q3'][i], hold=data['Category'][i])

    return HttpResponse('Sup')

def shift(l):
    n = randint(0,len(l))
    return l[n:] + l[:n]


def first(request):
    return HttpResponseRedirect('/stock/dashboard/')



def detailview(request, pid):
    if (not request.user.is_authenticated):
        return HttpResponse('login first')
    context = { 'user' : profile.objects.get(user_ref= request.user) ,'feeds': feeds , 'bigasslist': shift(singlestock.objects.all())[:30], 'object' : get_object_or_404(singlestock, pk=pid)}
    return render(request, 'stock/detail.html', context)

def about(request):
    return render(request, 'stock/about.html', {'feeds': feeds })


def services(request):
    return render(request, 'stock/services.html', {'feeds': feeds })
'''
def contact(request):
    return render(request, 'stock/contact.html', {})
'''

def contact(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            k = feedback.objects.create(name= request.POST['name'], content= request.POST['content'])
            return HttpResponse('Thanks')
    else:
        form = FeedbackForm()
    return render(request, 'stock/contact.html', {'form':form,'feeds': feeds })

def dashboard(request):
    if (not request.user.is_authenticated):
        return HttpResponse('login first')

    if(len(profile.objects.filter(user_ref= request.user))==0):
        new_profile = profile.objects.create(name = request.user.first_name, user_ref = request.user, company = "Not entered", email = request.user.email)
    else:
        context = {'user': profile.objects.get(user_ref=request.user), 'bigasslist': shift(singlestock.objects.all())[:30],
                   'feeds': feeds}
        return render(request, 'stock/dashboard.html', context)

    context = { 'user' : profile.objects.get(user_ref= request.user) , 'bigasslist': shift(singlestock.objects.all())[:30],'feeds': feeds }
    return render(request, 'stock/dashboard.html', context)


'''
class ListView(generic.ListView):
    template_name = 'stock/listview.html'

    def get_queryset(self):
        return singlestock.objects.all()


'''



def noti(request):
    if (not request.user.is_authenticated):
        return HttpResponse('login first')

    tat = singlestock.objects.all()
    hh = tat.order_by('high')[::-1][0:5]
    by = tat.order_by('yearly')[::-1][0:5]


    context = { 'by':by,'hh':hh,'user' : profile.objects.get(user_ref= request.user) ,'feeds': feeds , 'bigasslist': shift(singlestock.objects.all())[:30]}

    return render(request, 'stock/noti.html', context)


def addtolist(request , pid):
    if (not request.user.is_authenticated):
        return HttpResponse('login first')
    stock = get_object_or_404(singlestock, pk= pid)
    pro = get_object_or_404(profile, user_ref= request.user)

    pro.stocks.add(stock)
    pro.save()
    a = '/stock/' + str(pid)+'/'
    return HttpResponseRedirect(a)


def remove(request , pid):
    if (not request.user.is_authenticated):
        return HttpResponse('login first')
    stock = get_object_or_404(singlestock, pk= pid)
    pro = get_object_or_404(profile, user_ref= request.user)

    pro.stocks.remove(stock)
    pro.save()
    a = '/stock/' + str(pid)+'/'
    return HttpResponseRedirect(a)


def signup(request):
    return render(request, 'stock/signup.html', {})

def search(request):
    query = request.POST['searched']
    a = singlestock.objects.filter(name__icontains=query)
    return render(request, 'stock/listview.html', { 'object_list' : a ,'feeds': feeds , 'user' : profile.objects.get(user_ref= request.user) })

'''
def get_name(request):
    if request.method == 'POST':
        form = NameForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('detail', pk=post.pk)
    else:
        form = NameForm()
    return render(request, 'stock/form.html', {'form':form})
'''

def profileregister(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            if len(User.objects.filter(username= request.POST['email_ID']))!=0:
                return HttpResponse('email ID already registered')

            if request.POST['password'] == request.POST['confirm_password']:
                user = User.objects.create_user(username=request.POST['email_ID'], email=request.POST['email_ID'], password=request.POST['password'])
                profile.objects.create(user_ref= user, name=request.POST['name'], email= request.POST['email_ID'], age= 0, company= request.POST['company'])
                # authenticate(username= request.POST['email_ID'], password=request.POST['password'])
                #login(request, user)
                return HttpResponseRedirect('bakwas/')

            else:
                return HttpResponse("Passwords didn't match")

    else:
        form = ProfileForm()
    return render(request, 'stock/form.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            if len(User.objects.filter(username= request.POST['email_id']))!=0:
                user= authenticate(username= request.POST['email_id'], password= request.POST['password'])
                if user is None:
                    return HttpResponse("User doesn't exist")

                else:
                    login(request, user)
                    return HttpResponseRedirect('/stock/')
            else:
                return HttpResponse("Error")

    else:
        form = LoginForm()
    return render(request, 'stock/signup.html', {'form': form})


def logout_view(request):
    logout(request)
    print(5)
    return HttpResponseRedirect('/')

def paaa(request):
    if (not request.user.is_authenticated):
        return HttpResponse('login first')
    context = { 'user' : profile.objects.get(user_ref= request.user) ,'feeds': feeds , 'bigasslist': shift(singlestock.objects.all())[:30]}
    return render(request, 'stock/profiles.html', context)


def edit(request):
    if (not request.user.is_authenticated):
        return HttpResponse('login first')

    if request.method == 'POST':
        form = poForm(request.POST)
        if form.is_valid():
            k = profile.objects.get(user_ref= request.user)
            k.age = request.POST['age']
            k.company = request.POST['company']
            k.save()
            return HttpResponseRedirect('/stock/profile/')
    else:
        form = poForm()

    context = { 'user' : profile.objects.get(user_ref= request.user) ,'feeds': feeds , 'bigasslist': shift(singlestock.objects.all())[:30], 'form':form}
    return render(request, 'stock/editp.html', context)


def listview(request):
    return HttpResponseRedirect('/stock/all/0/1')


def pagi(request, fby, page):
    if (not request.user.is_authenticated):
        return HttpResponse('login first')
    tat = singlestock.objects.all()

    if fby == '0':
        tat = tat.order_by('name')
    elif fby == '1':
        tat = tat.order_by('high')
    elif fby == '2':
        tat = tat.order_by('yearly')
    elif fby == '3':
        tat = tat.order_by('name')[::-1]
    elif fby == '4':
        tat = tat.order_by('high')[::-1]
    elif fby == '5':
        tat = tat.order_by('yearly')[::-1]
    #return HttpResponse(str(fby)+' ' +str(pag))

    paginator = Paginator(tat, 9)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    page = int(page)

    #return HttpResponse(str(paginator.num_pages))
    context = { 'user' : profile.objects.get(user_ref= request.user) ,'feeds': feeds , 'object_list': users, 'bigasslist': shift(singlestock.objects.all())[:30], 'fby': fby, 'page': page, 'pn': page -1, 'pp': page + 1}


stock/templates/stock/bakwas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 Thanks for Registering <a href="/">Login here</a>
</body>
</html>

stock/templates/stock/contact.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/logo.jpg' %}" >
    <title>Contact</title>

    <link href="{% static 'css/styler.css' %}" rel="stylesheet">
    <style>
         body {
       padding-top: 54px;
    }

    @media (min-width: 992px) {
      body {
          padding-top: 56px;
        }

    .btn-outline-success:hover {
      background-color: white;
     }
    </style>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" style="font-family: 'Roboto Slab', serif;" href="{% url 'home' %}">Stock Juaari</a>

        <div class="" id="navbarResponsive">


          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'services' %}">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'contact' %}">Contact Us</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">

      <div class="row">
        <div class="col-lg-12" style="padding: 25px 0;">

          <div class="row">

          <div class="card card-outline-secondary my-4">
            <div class="card-header">
                <p style="position: absolute ; left: 50%; transform: translate(-50%,0); display: block">Contact the devs</p><br>
            </div>
            <div class="card-body">
              <h5>Khush Chopra</h5>
              <p>This being a bit intensive project, the responsibilities were appropriately divided among
the member developers and their efforts were validated by each of the others. The user
interface of the website needed to be very commodious and convenient for a very
pleasant user experience. Apart from this, the backend of the website required to be
easily readable and reusable as various developers were involved in its making. He
ensured that we implement jinja templating, thus our code is much more efficient and
easy to debug.</p>
              <small class="text-muted">16074008</small>
                <hr>
              <h5>Raghav Kabra</h5>
              <p>The database models acted as substrata for the project and required utmost diligence in
their creation. They were created with the thought in mind to optimise the data storage
needs of the user along with the speedy processing capabilities of the system to ensure
the best user experience.</p>
              <small class="text-muted">16074010</small>
                <hr>
              <h5>Saurabh Chauhan</h5>
              <p>It was essential for the website to provide the user with an assortment of services for the
most customizable experience. Thus, our developers implemented services like
StockScreener and Stockopedia for filtering and detailed examination of stocks
according to their marketing needs. They can view their customised notifications for
quick access to their stocks and take decisions in a swift manner.</p>
              <small class="text-muted">16074012</small>
                <hr>
              <h5>Suyash Shukla</h5>
              <p>He was involved in the mining, extraction and filtering of real stock data. We
implemented state of the art statistical models and relevant analytical algorithms, for the
determination of our collective predictions of the stock market to be as accurate as
possible.</p>
                 <small class="text-muted">16074014</small>
            </div>
          </div>

          </div>
          <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

      </div>

      <div class="row">
        <div class="col-lg-12" style="padding: 25px 0;">

          <div class="row">

          <div class="card card-outline-secondary my-4">
            <div class="card-header">
                <p style="position: absolute ; left: 50%; transform: translate(-50%,0); display: block">Feedback</p><br>
            </div>
            <div class="card-body">
              <h5>Khush Chopra</h5>
              <p>Contact our representative for any feedback or suggestions you may have for our services to ensure a smoother experience. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp;</p>
              <small class="text-muted">9838783612</small>
                <hr>
              <form method="post" action="">
              {% csrf_token %} <!--
              {{ form }} -->


              <tr><th><label for="id_name">Name:</label></th><td><input type="text" name="name" style="display: block; width: 350px" maxlength="50" required id="id_name" /></td></tr><br>
<tr><th><label for="id_content">Content:</label></th><td><input type="text" style="display: block; width: 100%;" name="content" maxlength="1000" required id="id_content" /></td></tr><br>
              <button type="submit" >Save</button>
            </form>
            </div>
          </div>

          </div>
          <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

      </div>
      <!-- /.row -->

    </div>


    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Stock Juaari 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/popper/popper.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

  </body>

</html>

stock/templates/stock/editp.html
{% extends 'stock/base.html' %}

{% block title %}Edit your profile{% endblock %}
{% block body %}
<div class="col-lg-9" style="min-height: 582px">
<br>

          <div class="card mt-4">
            <div class="card-body">
              <h6>Edit your profile</h6>
              <h3 class="card-title">{{ user.name }}</h3>
               <p class="card-text" >you cannot change your Email ID</p></a>

            </div>
          </div>
          <!-- /.card -->
          <div class="card card-outline-secondary my-4">
            <div class="card-header">
                <p style="position: absolute ; left: 50%; transform: translate(-50%,0); display: block">Your Profile</p><br>
            </div>
            <div class="card-body">

                <form method="post" action="">
                    {% csrf_token %}
                    <p><label for="id_age">Age:</label>
                    <input type="number" style="float: right;" name="age" required id="id_age" /><hr>
                    <label for="id_company">Company:</label>
                    <input type="text" name="company" style="float: right;" maxlength="50" required id="id_company" /><p>
                <br><button type="submit" >Save changes</button>
            </div>
          </div>

            <p> </p>
            <p> </p>
            <p> </p>
            <p> </p>

          <!-- /.card -->

        </div>



      </div>



{% endblock %}

stock/templates/stock/list_iter.html

{% for object in object_list %}
            <div class="col-lg-4 col-md-6 mb-4">
              <a href="{% url 'detail' object.pk %}" style="text-decoration: none">
              <div class="card h-100">
                <div class="card-body">
                  <h4 class="card-title" style="color: blue; text-size: 25px;">
                    {{ object.name }}
                  </h4>
                  <p class="card-text" style="padding-bottom: 0; margin-bottom: 0;">{{ object.sector }}</p>
                  <p class="card-text text-muted" style="float: right; display: block; transform: translate(0,-10px)">Sector</p><hr>

                  <p class="card-text" style="padding-bottom: 0; margin-bottom: 0;">{{ object.cap }}</p>
                  <p class="card-text text-muted" style="float: right; display: block; transform: translate(0,-10px)">Cap</p><hr>
                 
                </div>
                <div class="card-footer">
                  <small class="text-muted">powered by: asf</small>
                </div>
              </div>
              </a>
            </div>
{% endfor %}




stock/templates/stock/signup.html
{% load static %}
<html>
    <head>
        <link rel="icon" href="{% static 'images/logo.jpg' %}" >
        <link rel="stylesheet" href="static/CSS/first.css">
        <title>
            Stock Juaari
        </title>
        <style>
            body {
            height: 100%;
            width: 100%;
            padding: 0;
            margin: 0;
        }

        input[type=text], select {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type=password], select {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type=submit] {
            display: block;
            width: 100%;
            background-color: #1f468e;
            color: aliceblue;
            padding: 14px 20px;
            margin: 8px 0;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 20px;
            transition-duration: 200ms;
        }

        input[type=submit]:hover {
            color: #1f468e;
            background-color: aliceblue;
        }


        h2 {
            font-family: sans-serif;
            color: azure;
            text-align: center;
            font-size: 30px;
        }

        img {
            display: block;
            margin: auto;
            width: auto;
        }

        .login {
            height: 70%;
            position: relative;
            top: 15%;
            width: 70%;
            min-width: 500px;
            display: table;
            margin: 0 auto;
            padding-left: 28px;
            padding-right: 28px;
            border: 2px solid #1f468e;
            vertical-align: middle;
            border-radius: 4px;
            border-radius: 8px;
            background-color: #1f1f1f;
            max-width: 700px;
        }

        .logi {
            height: auto;
            position: relative;
            top: 10%;
            width: 70%;
            min-width: 500px;
            display: table;
            margin: 0 auto;
            padding: 20px 28px ;
            border: 4px solid #1f468e;
            vertical-align: middle;
            border-radius: 8px;
            background-color: aliceblue;

        }

        .phead {
            display: inline;
            font-family: sans-serif;
            color: #1f1f1f;
            font-size: 35px;
        }

        .pline {
            display: inline;
            font-family: sans-serif;
            color: #1f1f1f;
            font-size: 16px;
            line-height: normal;
        }

        div.person {
            display: block;
            vertical-align: auto;
            padding-bottom: 35px;
        }

        .bottomline {
            border-bottom: 4px dashed #333;
        }

        a {
            text-decoration: none;
            color: inherit;
        }

        .object{
            height: 100%;
            width: 100%;
            background-size: cover;
            background-attachment: fixed;
            padding: 0px;
            margin: 0px;
        }

        .small {
            height: auto;
            background-color: #1f1f1f;
            margin: 1px solid black;
        }
        .two {
            background-image: url(http://i.imgur.com/3ssLSdG.jpg);
            height: auto;
            padding-top: 50px;
            padding-bottom: 50px;
        }

        .one {
            background-image: url(http://i.imgur.com/ke3HQLQ.jpg);
        }

        h1 {
            padding: 0px;
            margin: 0px;
            text-align: center;
            position: relative;
            top: 5%;
            font-family: sans-serif;
            color: #1f1f1f;
        }

        .inside {
            padding: 20px 10%;
        }

        .info {
            border-radius: 3px;
            box-shadow: 1px 1px 5px #1f468e;
            color: aliceblue;
        }

        p {
            padding: 30px;
            margin: 0px;
            font-family: sans-serif;
            line-height: 22px;

        }

        h2 {
            padding-top: 20px;
            margin: 0px;
        }
        </style>
    </head>
    <body>
        <div class="object one">
            <div class="login">
                <br>
                <br>
                <img src="http://i.imgur.com/IWz4hU8.png" height="70px">
                <h2>Welcome To Stock Juaari</h2>
                <br>
                <br>
                <br>
                <form action="" method="post">
                    {% csrf_token %}
    <input type="text" id="fname" name="email_id" maxlength="50" placeholder="Enter Email ID" required id="id_email_id" >
    <input type="password" id="lname" name="password" placeholder="Please Enter Password" minlength="8" required id="id_password">
                     <input type="submit" value="Login">
  </form>

                <div class="bottomline"></div>
                <div style="text-align: center; vertical-align: middle; "><p style="color: aliceblue; font-size: 20px; text-decoration: none; padding-bottom: 0px;">Not a member? <a href="{% url 'register' %}" style="color: #1f468e">Sign Up</a></p></div>
                <div style="text-align: center; vertical-align: middle; "><p style="color: aliceblue; font-size: 20px; text-decoration: none; padding-bottom: 10px;"><a href="{% url 'social:begin' 'github' %}" style="color: aqua">Login with GitHub</a></div>
            </div>
        </div>
        <div class="object small">
            <div class="inside">
                <div class="info">
                    <h2 style="text-align: center; font-family: sans-serif">About Stock Juaari</h2>
                    <p>We present you with an interactive platform StockJuaari, powered by simple and smart
features designed to cater all your investment needs. Stock screener tool helps you to
choose your stock investments based on fundamental company analysis while it will also
aid you to select best performing stocks based on sound technical analysis. Our stock
analysis platform is power packed with useful features like advanced portfolio tracker,
market watch, stock screener, technical analysis of stocks and many more.</p>
                </div>
            </div>
        </div>
        <div class="object two">
            <h1>About the Developers</h1>
            <div class="logi">
                <div class="person">
                    <h3 class="phead">Khush Chopra</h3>
                    <p class="pline">I do like Pina Coladas and getting caught in the rain.</p>
                </div>
                <div class="person">
                    <h3 class="phead">Raghav Kabra</h3>
                    <p class="pline">Bilwara is the manchester of Asia.</p>
                </div>
                <div class="person">
                    <h3 class="phead">Saurabh Chauhan</h3>
                    <p class="pline">I am  only human</p>
                </div>
                <div class="person">
                    <h3 class="phead">Suyash Sukhla</h3>
                    <p class="pline">follow me down the valley below</p>
                </div>
            </div>
        </div>
    </body>

</html>

stock/templates/stock/tickeriter.html


<div class="ticker-wrap" style="margin-bottom: 10px;">
    <div class="ticker">{% for kam in bigasslist %}
    <div class="ticker__item">


        <span>{{ kam.name }}</span>
         <span class="dwnchng"> {{ kam.last_trade_price }}
        &nbsp; &nbsp;  </span></div>
     {% endfor %}
    </div>
</div>